# Generated by Django 4.0.3 on 2022-09-30 19:11

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNPJ',
            fields=[
                ('cnpj', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(14)], verbose_name='CNPJ')),
                ('updated_at', models.DateTimeField(verbose_name='Atualizado em')),
                ('is_mei', models.BooleanField(verbose_name='É MEI')),
            ],
            options={
                'verbose_name': 'CNPJ',
                'verbose_name_plural': 'CNPJ',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição da MEI')),
                ('corporate_name', models.CharField(max_length=100, unique=True, verbose_name='Razão social')),
                ('city', models.CharField(max_length=80, verbose_name='Cidade')),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='CEP')),
                ('uf', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='UF')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 9, 30, 19, 11, 29, 409917), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 9, 30, 19, 11, 29, 409933))),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('cnpj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies.cnpj')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
