# Generated by Django 4.0.3 on 2022-03-24 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cnpj', models.CharField(max_length=16, unique=True, verbose_name='CNPJ')),
                ('corporate_name', models.CharField(max_length=128, verbose_name='Razão social')),
                ('fantasy_name', models.CharField(max_length=64, verbose_name='Nome fantasia')),
                ('email', models.EmailField(max_length=64, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=32, verbose_name='Telefone')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 3, 24, 17, 51, 32, 879214), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 3, 24, 17, 51, 32, 879249))),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
