# Generated by Django 4.0.3 on 2022-03-24 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 24, 18, 8, 18, 27277), editable=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 24, 18, 8, 18, 27293)),
        ),
    ]
