# Generated by Django 4.0.3 on 2022-10-17 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_created_at_alter_company_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 17, 15, 0, 10, 305111), editable=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 17, 15, 0, 10, 305127)),
        ),
    ]
