# Generated by Django 4.0.3 on 2022-09-30 19:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('apurado', models.CharField(max_length=3, verbose_name='Apuração')),
                ('situacao', models.CharField(max_length=32, verbose_name='Status')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Principal')),
                ('multa', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Multa')),
                ('juros', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Juros')),
                ('total', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Total')),
                ('data_vencimento', models.DateTimeField(blank=True, null=True, verbose_name='Vencimento')),
                ('data_acolhimento', models.DateTimeField(blank=True, null=True, verbose_name='Acolhimento')),
                ('url_das', models.CharField(max_length=255, verbose_name='URL DAS')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 9, 30, 19, 11, 29, 413040))),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DAS',
                'verbose_name_plural': 'DAS',
            },
        ),
    ]
