# Generated by Django 4.0.3 on 2022-09-30 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_alter_das_juros_alter_das_multa_alter_das_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='das',
            name='data_acolhimento',
            field=models.DateField(blank=True, null=True, verbose_name='Acolhimento'),
        ),
        migrations.AlterField(
            model_name='das',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento'),
        ),
        migrations.AlterField(
            model_name='das',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 20, 15, 41, 482995)),
        ),
        migrations.AlterField(
            model_name='das',
            name='url_das',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL DAS'),
        ),
    ]
