# Generated by Django 4.0.3 on 2022-10-14 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0003_alter_das_data_acolhimento_alter_das_data_vencimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='das',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 14, 17, 32, 8, 861174)),
        ),
    ]
