# Generated by Django 4.0.3 on 2022-10-17 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0005_alter_das_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='das',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 17, 15, 0, 10, 308282)),
        ),
    ]
