# Generated by Django 4.0.3 on 2022-10-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_provider_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Limpeza'), (2, 'Saúde'), (3, 'Alimentação'), (4, 'Moda'), (5, 'Bebidas'), (6, 'Tecnologia'), (7, 'Brinquedos'), (8, 'Matéria-prima'), (9, 'Ferramentas'), (10, 'Outros')], verbose_name='Categoria'),
        ),
    ]
