# Generated by Django 4.0.3 on 2022-09-30 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do compromisso')),
                ('finished', models.BooleanField(verbose_name='Finalizado')),
                ('forecast_date', models.DateField(default=datetime.datetime(2022, 9, 30, 19, 11, 29, 411812), verbose_name='Previsão de término')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 9, 30, 19, 11, 29, 411825), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 9, 30, 19, 11, 29, 411836))),
                ('finished_at', models.DateTimeField(default=datetime.datetime(2022, 9, 30, 19, 11, 29, 411850), editable=False)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
