# Generated by Django 4.0.3 on 2022-09-30 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 19, 53, 42, 859411), editable=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='finished_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 19, 53, 42, 859436), editable=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='forecast_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 30, 19, 53, 42, 859396), verbose_name='Previsão de término'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 19, 53, 42, 859423)),
        ),
    ]
